### PR TITLE
Added CactusCon

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by jsmonje** [comment]
I think your distribution may be a bit too large.

I should not be receiving these...

john monje

6121 S Four Peaks Pl
Chandler, AZ 85249
1204600132 - ASU Id
480 231 7552

From: mzovne 
Sent: Thursday, March 05, 2015 9:56 AM
To: asu-cis-capstone/course-info 
Subject: [course-info] Added CactusCon (#64)


--------------------------------------------------------------------------------

You can view, comment on, or merge this pull request online at:
  https://github.com/asu-cis-capstone/course-info/pull/64

Commit Summary
  a.. Added CactusCon 
File Changes
  a.. M individual_assignments.md (2) 
Patch Links:
  a.. https://github.com/asu-cis-capstone/course-info/pull/64.patch 
  b.. https://github.com/asu-cis-capstone/course-info/pull/64.diff

**Comment by mzovne** [comment]
Hi John,

 

Do you currently have the course-info repository starred?

 

Mark Zovne

**Comment by jsmonje** [comment]
Hi Mark,

I took the course fall 14 = last semester.
I seem to be stuck in some distribution list somewhere????

john monje

6121 S Four Peaks Pl
Chandler, AZ 85249
1204600132 - ASU Id
480 231 7552

**Comment by mzovne** [comment]
No worries. It looks like you are “watching” the capstone repository, or a forked version of it. Un-watch and Un-star, all repositories/forks that you have contributed to. This will stop the email notifications from GitHub.

 

https://github.com/jsmonje

 

 

You are listed as “watching” this repository

https://github.com/asu-cis-capstone/course-info/watchers

 

Additional information:

https://github.com/blog/1204-notifications-stars

Notifications are now powered by the repositories you are watching <https://github.com/watching> . If you are watching a repository, you will receive notifications for all discussions.

*         Issues and their comments

*         Pull Requests and their comments

*         Comments on any commits

If you are not watching a repository, you'll only be notified for discussions for which you participate.

*          <https://github.com/blog/821> @mentions

*         Assignments

*         Commits you author or commit

*         Any discussion you've commented on

You're automatically watching a bunch of repositories based on your permissions — it's probably a good idea to go through and unwatch repositories <https://github.com/watching>  you're not interested in.

 



 

Hope this helps!

 

--Mark Zovne

 

 

On Mar 5, 2015 7:42 PM, "john monje" <notifications@github.com <mailto:notifications@github.com> > wrote:

Hi Mark,

I took the course fall 14 = last semester.
I seem to be stuck in some distribution list somewhere????

john monje

6121 S Four Peaks Pl
Chandler, AZ 85249
1204600132 - ASU Id
480 231 7552 <tel:480%20231%207552>

**Comment by jsmonje** [comment]
hi Joe - i hope this semester is going well for you.
Is there a special reason for me to get a cc on this?

thanks
john monje

rom:Joseph Clark <notifications@github.com>
reply-to:asu-cis-capstone/course-info
<
reply@reply.github.com
>
to:asu-cis-capstone/course-info <course-info@noreply.github.com>
cc:john monje <jsmonje@gmail.com>
date:Thu, Apr 2, 2015 at 9:03 AMsubject:Re: [course-info] Added CactusCon
(#64)mailing list:course-info.asu-cis-capstone.github.com Filter messages
from this mailing
listmailed-by:github.comsigned-by:github.comunsubscribe:Unsubscribe
from this mailing-list:Important mainly because it was sent directly to you.

On Thu, Apr 2, 2015 at 9:03 AM, Joseph Clark <notifications@github.com>
wrote:

> Merged #64 <https://github.com/asu-cis-capstone/course-info/pull/64>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/asu-cis-capstone/course-info/pull/64#event-271851916>.
>



-- 

john monje



6121 S Four Peaks Pl

Chandler, AZ 85249

480 231 7552

jsmonje@gmail.com

**Comment by joeclark-phd** [comment]
John, I think you may need to "unwatch" the asu-cis-capstone/course-info
repository on Github.  That would be my guess.  Here it is so you can check
for yourself: https://github.com/asu-cis-capstone/course-info

Alternatively, try going to this GitHub "settings" page:
https://github.com/settings/notifications
Under the "notification center", you can turn email and web notifications
on and off.

Hope you're well,
JWC

On Thu, Apr 2, 2015 at 1:41 PM, john monje <notifications@github.com> wrote:

> hi Joe - i hope this semester is going well for you.
> Is there a special reason for me to get a cc on this?
>
> thanks
> john monje
>
> rom:Joseph Clark <notifications@github.com>
> reply-to:asu-cis-capstone/course-info
> <
> reply@reply.github.com
> >
> to:asu-cis-capstone/course-info <course-info@noreply.github.com>
> cc:john monje <jsmonje@gmail.com>
> date:Thu, Apr 2, 2015 at 9:03 AMsubject:Re: [course-info] Added CactusCon
> (#64)mailing list:course-info.asu-cis-capstone.github.com Filter messages
> from this mailing
> listmailed-by:github.comsigned-by:github.comunsubscribe:Unsubscribe
> from this mailing-list:Important mainly because it was sent directly to
> you.
>
> On Thu, Apr 2, 2015 at 9:03 AM, Joseph Clark <notifications@github.com>
> wrote:
>
> > Merged #64 <https://github.com/asu-cis-capstone/course-info/pull/64>.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/asu-cis-capstone/course-info/pull/64#event-271851916
> >.
> >
>
>
>
> --
>
> john monje
>
>
>
> 6121 S Four Peaks Pl
>
> Chandler, AZ 85249
>
> 480 231 7552
>
> jsmonje@gmail.com
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/asu-cis-capstone/course-info/pull/64#issuecomment-89040092>
> .
>



-- 
// joseph w. clark, clinical asst. professor of information systems
\\ arizona state university, w. p. carey school of business
// +1-480-965-0024, @joeclarknet

**Pull request merged**
